services:
  - type: pserv
    name: integravida-db
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheck:
      path: /
      protocol: HTTP
    envVars:
      - key: POSTGRES_DB
        value: integravida
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        generateValue: true
